[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cinderblock/amscope-reader"
rust-version = "1.88"

[workspace.dependencies]
amscope-protocol = { path = "crates/amscope-protocol" }
amscope = { path = "crates/amscope" }
amscope-isp = { path = "crates/amscope-isp" }
nusb = "0.2.7"
thiserror = "2"
tracing = "0.1"
bzip2 = "0.6"
clap = { version = "4.6", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
rayon = "1.12"
png = "0.18"
tiff = "0.11"
jpeg-encoder = "0.7"
